pdf_structure:
  metadata:
    title: "Название отчёта"
    author: "Автор"
    creation_date: "Дата создания"
    subject: "Описание документа"
    hash_sum: "Хэш-сумма"

  objects:
    - type: "text"
      name: "report_time" # Время отчёта
      method: "absolute"
      position:
          x: 90
          y: 10
      dimensions:
        width: 150
        height: 20
      page_number: 1

    - type: "table"
      name: "stoppages_data" # Данные о простоях в таблице
      method: "by_pointers"
      headers:
        - pointer:
            type: "drawing"
            criteria:
              height: 3.0
            multiple: true
          position_offset:
            x: 0
            y: -10
          dimensions:
            width: 500
            height: 15
        - pointer:
            type: "drawing"
            criteria:
              height: 3.0
            multiple: false
          position_offset:
            x: 0
            y: 20
          dimensions:
            width: 500
            height: 15
      row_pointers:
        - pointer:
            type: "drawing"
            criteria:
              height: 1.5
            multiple: true
          row_height: 20
      table_structure:
        headers: [ "Название компании", "Параметр", "Значение", "Единицы" ]
        column_widths: [ 150, 150, 100, 100 ]
      end_of_table_marker:
        type: "drawing"
        criteria:
          height: 5.0
        multiple: false
        position_offset:
          x: 0
          y: 10
        dimensions:
          width: 500
          height: 5

    - type: "text"
      name: "total_production"
      method: "relative"
      relative_to:
        type: "table"
        name: "production_data"
        multiple: false
      offset:
        x: 0
        y: 20
      dimensions:
        width: 200
        height: 15
      page_number: 2
