pdf_structure:
  metadata:
    title: "Название отчёта"
    author: "Автор"
    creation_date: "Дата создания"
    subject: "Описание документа"
    hash_sum: "Хэш-сумма"

  objects:
    - type: "text"
      name: "report_time" # Время отчёта
      method: "absolute"
      offset:
        x: 520
        y: 20
      dimensions:
        width: 130
        height: 20
      page_number: 0

    - type: "table"
      name: "stoppages_data" # Данные о простоях в таблице
      method: "by_pointers"
      blocks_pointer:
        type: "drawing"
        criteria:
          height: 3.0
        multiple: true
        offset:
          x: 0
          y: -17
        dimensions:
          width: 570
          height: 17
        headers:
          names: [ "company_name" ]
          column_widths: [ 570 ]
      row_pointer:
        type: "drawing"
        criteria:
          height: 0.1
        multiple: true
        offset:
          x: -5
          y: -35
        dimensions:
          width: 345
          height: 35
      table_structure:
        headers:
          names: [ "start_time", "end_time", "downtime_hours", "factory_number", "serial_number" ]
          column_widths: [ 95, 90, 43, 57, 60 ]
      end_of_table_marker:
        type: "none"