pdf_structure:
  objects:
    - type: "text"
      name: [ "contract_number", "project_description", "construction_code", "nomenclature_code", "contractor_name", "customer_name" ]
      method: "absolute"
      offset:
        x: 0
        y: 0
      dimensions:
        width: 600
        height: 600
      page_number: 0
      # Массив регулярных выражений для каждого элемента
      patterns:
        - target: "contract_number"
          regex: "ДОГОВОР СУБПОДРЯДА\\s*№\\s*([^\\n]+)"
          group_format: "{}"
        - target: "project_description"
          regex: "\\n\\s*([\\s\\S]+?)\\s*код стройки"
          group_format: "{}"
        - target: "construction_code"
          regex: "код стройки\\s*([^\\s\\n]+)"
          group_format: "{}"
        - target: "nomenclature_code"
          regex: "\\(код\\s+(?:номенклатурной группы проекта|проектный код)\\s*([^\\s\\n\\)]+)\\)"
          group_format: "{}"
        - target: "contractor_name"
          regex: "между\\s*([А-ЯЁа-яё«»\\s]+?)\\s*и"
          group_format: "{}"
        - target: "customer_name"
          regex: "\\s*и\\s*([А-ЯЁа-яё«»\\s]+)\\s*\\Z"
          group_format: "{}"

    - type: "text"
      name: "date"
      method: "absolute"
      offset:
        x: 370
        y: 0
      dimensions:
        width: 200
        height: 70
      page_number: 3

    - type: "text"
      name: [ "price_without_vat", "price_with_vat" ]  # Два значения: цена без НДС и цена с НДС
      method: "by_pointers"
      pointer:
        type: "text"
        criteria:
          regex: "Цена Работ не должна"  # Начальное регулярное выражение для поиска указателя
      offset:
        x: -150
        y: 0
      dimensions:
        width: 600
        height: 130
      page_number: 0
      patterns:
        - target: "price_with_vat"
          regex: "Цена Работ не должна превышать\\s*([\\d\\s]+)\\s*\\([\\s\\S]*?\\)\\s*руб(?:[а-яё]*)\\s*([\\d\\s]+)\\s*коп(?:[а-яё]*)"
          group_format: "{} рублей {} копеек"  # Формат суммы
        - target: "vat"
          regex: "налогах и сборах в размере\\s*([\\d\\s]+)\\s*\\([\\s\\S]*?\\)\\s*руб(?:[а-яё]*)\\s*([\\d\\s]+)\\s*коп(?:[а-яё]*)"
          group_format: "{} рублей {} копеек"  # Формат суммы
